var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
var SamplePanel1 = function () { return (_jsxs(_Fragment, { children: [_jsx("h3", __assign({ className: "text-lg leading-6 font-medium text-gray-900" }, { children: "Delete your account" }), void 0), _jsx("div", __assign({ className: "mt-2 max-w-xl text-sm text-gray-500" }, { children: _jsx("p", { children: "Once you delete your account, you will lose all data associated with it." }, void 0) }), void 0), _jsx("div", __assign({ className: "mt-5" }, { children: _jsx("button", __assign({ type: "button", className: "inline-flex items-center justify-center px-4 py-2 border border-transparent font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:text-sm" }, { children: "Delete account" }), void 0) }), void 0)] }, void 0)); };
var SamplePanel2 = (_jsxs(_Fragment, { children: [_jsx("h3", __assign({ className: "text-lg leading-6 font-medium text-gray-900" }, { children: "Continuous Integration" }), void 0), _jsx("div", __assign({ className: "mt-2 max-w-xl text-sm text-gray-500" }, { children: _jsx("p", { children: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, totam at reprehenderit maxime aut beatae ad." }, void 0) }), void 0), _jsx("div", __assign({ className: "mt-3 text-sm" }, { children: _jsxs("a", __assign({ href: "#", className: "font-medium text-primary-600 hover:text-primary-500" }, { children: [' ', "Learn more about our CI features ", _jsx("span", __assign({ "aria-hidden": "true" }, { children: "\u2192" }), void 0)] }), void 0) }), void 0)] }, void 0));
var SamplePanel3 = function () { return (_jsxs(_Fragment, { children: [_jsx("h3", __assign({ className: "text-lg leading-6 font-medium text-gray-900" }, { children: "Manage subscription" }), void 0), _jsxs("div", __assign({ className: "mt-2 sm:flex sm:items-start sm:justify-between" }, { children: [_jsx("div", __assign({ className: "max-w-xl text-sm text-gray-500" }, { children: _jsx("p", { children: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae voluptatibus corrupti atque repudiandae nam." }, void 0) }), void 0), _jsx("div", __assign({ className: "mt-5 sm:mt-0 sm:ml-6 sm:flex-shrink-0 sm:flex sm:items-center" }, { children: _jsx("button", __assign({ type: "button", className: "inline-flex items-center px-4 py-2 border border-transparent shadow-sm font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 sm:text-sm" }, { children: "Change plan" }), void 0) }), void 0)] }), void 0)] }, void 0)); };
var SamplePanel4 = function () { return (_jsxs(_Fragment, { children: [_jsx("h3", __assign({ className: "text-lg leading-6 font-medium text-gray-900" }, { children: "Update your email" }), void 0), _jsx("div", __assign({ className: "mt-2 max-w-xl text-sm text-gray-500" }, { children: _jsx("p", { children: "Change the email address you want associated with your account." }, void 0) }), void 0), _jsxs("form", __assign({ className: "mt-5 sm:flex sm:items-center" }, { children: [_jsxs("div", __assign({ className: "w-full sm:max-w-xs" }, { children: [_jsx("label", __assign({ htmlFor: "email", className: "sr-only" }, { children: "Email" }), void 0), _jsx("input", { type: "text", name: "email", id: "email", className: "shadow-sm focus:ring-primary-500 focus:border-primary-500 block w-full sm:text-sm border-gray-300 rounded-md", placeholder: "you@example.com" }, void 0)] }), void 0), _jsx("button", __assign({ type: "submit", className: "mt-3 w-full inline-flex items-center justify-center px-4 py-2 border border-transparent shadow-sm font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm" }, { children: "Save" }), void 0)] }), void 0)] }, void 0)); };
var SamplePanel5 = function () { return (_jsxs(_Fragment, { children: [_jsx("h3", __assign({ className: "text-lg leading-6 font-medium text-gray-900" }, { children: "Payment method" }), void 0), _jsx("div", __assign({ className: "mt-5" }, { children: _jsxs("div", __assign({ className: "rounded-md bg-gray-50 px-6 py-5 sm:flex sm:items-start sm:justify-between" }, { children: [_jsx("h4", __assign({ className: "sr-only" }, { children: "Visa" }), void 0), _jsxs("div", __assign({ className: "sm:flex sm:items-start" }, { children: [_jsxs("svg", __assign({ className: "h-8 w-auto sm:flex-shrink-0 sm:h-6", viewBox: "0 0 36 24", "aria-hidden": "true" }, { children: [_jsx("rect", { width: 36, height: 24, fill: "#224DBA", rx: 4 }, void 0), _jsx("path", { fill: "#fff", d: "M10.925 15.673H8.874l-1.538-6c-.073-.276-.228-.52-.456-.635A6.575 6.575 0 005 8.403v-.231h3.304c.456 0 .798.347.855.75l.798 4.328 2.05-5.078h1.994l-3.076 7.5zm4.216 0h-1.937L14.8 8.172h1.937l-1.595 7.5zm4.101-5.422c.057-.404.399-.635.798-.635a3.54 3.54 0 011.88.346l.342-1.615A4.808 4.808 0 0020.496 8c-1.88 0-3.248 1.039-3.248 2.481 0 1.097.969 1.673 1.653 2.02.74.346 1.025.577.968.923 0 .519-.57.75-1.139.75a4.795 4.795 0 01-1.994-.462l-.342 1.616a5.48 5.48 0 002.108.404c2.108.057 3.418-.981 3.418-2.539 0-1.962-2.678-2.077-2.678-2.942zm9.457 5.422L27.16 8.172h-1.652a.858.858 0 00-.798.577l-2.848 6.924h1.994l.398-1.096h2.45l.228 1.096h1.766zm-2.905-5.482l.57 2.827h-1.596l1.026-2.827z" }, void 0)] }), void 0), _jsxs("div", __assign({ className: "mt-3 sm:mt-0 sm:ml-4" }, { children: [_jsx("div", __assign({ className: "text-sm font-medium text-gray-900" }, { children: "Ending with 4242" }), void 0), _jsxs("div", __assign({ className: "mt-1 text-sm text-gray-600 sm:flex sm:items-center" }, { children: [_jsx("div", { children: "Expires 12/20" }, void 0), _jsx("span", __assign({ className: "hidden sm:mx-2 sm:inline", "aria-hidden": "true" }, { children: "\u00B7" }), void 0), _jsx("div", __assign({ className: "mt-1 sm:mt-0" }, { children: "Last updated on 22 Aug 2017" }), void 0)] }), void 0)] }), void 0)] }), void 0), _jsx("div", __assign({ className: "mt-4 sm:mt-0 sm:ml-6 sm:flex-shrink-0" }, { children: _jsx("button", __assign({ type: "button", className: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 sm:text-sm" }, { children: "Edit" }), void 0) }), void 0)] }), void 0) }), void 0)] }, void 0)); };
var ActionPanelComponent = function (_a) {
    var children = _a.children;
    return (_jsx("div", __assign({ className: "bg-white shadow sm:rounded-lg" }, { children: _jsx("div", __assign({ className: "px-4 py-5 sm:p-6" }, { children: children !== null && children !== void 0 ? children : _jsx(SamplePanel5, {}, void 0) }), void 0) }), void 0));
};
export var ActionPanel = Object.assign(ActionPanelComponent, {});
export default ActionPanel;
