var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Fragment, useState } from 'react';
import { Dialog, Transition } from '@headlessui/react';
import { CalendarIcon, HomeIcon, MapIcon, MenuIcon, SearchCircleIcon, SpeakerphoneIcon, UserGroupIcon, XIcon, } from '@heroicons/react/outline';
import { classNames } from '../helpers/methods';
var navigation = [
    { name: 'Dashboard', href: '#', icon: HomeIcon, current: true },
    { name: 'Calendar', href: '#', icon: CalendarIcon, current: false },
    { name: 'Teams', href: '#', icon: UserGroupIcon, current: false },
    { name: 'Directory', href: '#', icon: SearchCircleIcon, current: false },
    { name: 'Announcements', href: '#', icon: SpeakerphoneIcon, current: false },
    { name: 'Office Map', href: '#', icon: MapIcon, current: false },
];
export var FullWidthThreeColumn = function () {
    var _a = useState(false), sidebarOpen = _a[0], setSidebarOpen = _a[1];
    return (_jsxs("div", __assign({ className: "h-96 flex overflow-hidden bg-white" }, { children: [_jsx(Transition.Root, __assign({ show: sidebarOpen, as: Fragment }, { children: _jsxs(Dialog, __assign({ as: "div", className: "fixed inset-0 flex z-40 lg:hidden", onClose: setSidebarOpen }, { children: [_jsx(Transition.Child, __assign({ as: Fragment, enter: "transition-opacity ease-linear duration-300", enterFrom: "opacity-0", enterTo: "opacity-100", leave: "transition-opacity ease-linear duration-300", leaveFrom: "opacity-100", leaveTo: "opacity-0" }, { children: _jsx(Dialog.Overlay, { className: "fixed inset-0 bg-gray-600 bg-opacity-75" }, void 0) }), void 0), _jsx(Transition.Child, __assign({ as: Fragment, enter: "transition ease-in-out duration-300 transform", enterFrom: "-translate-x-full", enterTo: "translate-x-0", leave: "transition ease-in-out duration-300 transform", leaveFrom: "translate-x-0", leaveTo: "-translate-x-full" }, { children: _jsxs("div", __assign({ className: "relative flex-1 flex flex-col max-w-xs w-full bg-white focus:outline-none" }, { children: [_jsx(Transition.Child, __assign({ as: Fragment, enter: "ease-in-out duration-300", enterFrom: "opacity-0", enterTo: "opacity-100", leave: "ease-in-out duration-300", leaveFrom: "opacity-100", leaveTo: "opacity-0" }, { children: _jsx("div", __assign({ className: "absolute top-0 right-0 -mr-12 pt-2" }, { children: _jsxs("button", __assign({ type: "button", className: "ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white", onClick: function () { return setSidebarOpen(false); } }, { children: [_jsx("span", __assign({ className: "sr-only" }, { children: "Close sidebar" }), void 0), _jsx(XIcon, { className: "h-6 w-6 text-white", "aria-hidden": "true" }, void 0)] }), void 0) }), void 0) }), void 0), _jsxs("div", __assign({ className: "flex-1 h-0 pt-5 pb-4 overflow-y-auto" }, { children: [_jsx("div", __assign({ className: "flex-shrink-0 flex items-center px-4" }, { children: _jsx("img", { className: "h-8 w-auto", src: "https://tailwindui.com/img/logos/workflow-logo-indigo-600-mark-gray-900-text.svg", alt: "Workflow" }, void 0) }), void 0), _jsx("nav", __assign({ "aria-label": "Sidebar", className: "mt-5" }, { children: _jsx("div", __assign({ className: "px-2 space-y-1" }, { children: navigation.map(function (item) { return (_jsxs("a", __assign({ href: item.href, className: classNames(item.current
                                                            ? 'bg-gray-100 text-gray-900'
                                                            : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900', 'group flex items-center px-2 py-2 text-base font-medium rounded-md') }, { children: [_jsx(item.icon, { className: classNames(item.current
                                                                    ? 'text-gray-500'
                                                                    : 'text-gray-400 group-hover:text-gray-500', 'mr-4 h-6 w-6'), "aria-hidden": "true" }, void 0), item.name] }), item.name)); }) }), void 0) }), void 0)] }), void 0), _jsx("div", __assign({ className: "flex-shrink-0 flex border-t border-gray-200 p-4" }, { children: _jsx("a", __assign({ href: "#", className: "flex-shrink-0 group block" }, { children: _jsxs("div", __assign({ className: "flex items-center" }, { children: [_jsx("div", { children: _jsx("img", { className: "inline-block h-10 w-10 rounded-full", src: "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=256&h=256&q=80", alt: "" }, void 0) }, void 0), _jsxs("div", __assign({ className: "ml-3" }, { children: [_jsx("p", __assign({ className: "text-base font-medium text-gray-700 group-hover:text-gray-900" }, { children: "Whitney Francis" }), void 0), _jsx("p", __assign({ className: "text-sm font-medium text-gray-500 group-hover:text-gray-700" }, { children: "View profile" }), void 0)] }), void 0)] }), void 0) }), void 0) }), void 0)] }), void 0) }), void 0), _jsx("div", { className: "flex-shrink-0 w-14", "aria-hidden": "true" }, void 0)] }), void 0) }), void 0), _jsx("div", __assign({ className: "hidden lg:flex lg:flex-shrink-0" }, { children: _jsx("div", __assign({ className: "flex flex-col w-64" }, { children: _jsxs("div", __assign({ className: "flex-1 flex flex-col min-h-0 border-r border-gray-200 bg-gray-100" }, { children: [_jsxs("div", __assign({ className: "flex-1 flex flex-col pt-5 pb-4 overflow-y-auto" }, { children: [_jsx("div", __assign({ className: "flex items-center flex-shrink-0 px-4" }, { children: _jsx("img", { className: "h-8 w-auto", src: "https://tailwindui.com/img/logos/workflow-logo-indigo-600-mark-gray-900-text.svg", alt: "Workflow" }, void 0) }), void 0), _jsx("nav", __assign({ className: "mt-5 flex-1", "aria-label": "Sidebar" }, { children: _jsx("div", __assign({ className: "px-2 space-y-1" }, { children: navigation.map(function (item) { return (_jsxs("a", __assign({ href: item.href, className: classNames(item.current
                                                    ? 'bg-gray-200 text-gray-900'
                                                    : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900', 'group flex items-center px-2 py-2 text-sm font-medium rounded-md') }, { children: [_jsx(item.icon, { className: classNames(item.current
                                                            ? 'text-gray-500'
                                                            : 'text-gray-400 group-hover:text-gray-500', 'mr-3 h-6 w-6'), "aria-hidden": "true" }, void 0), item.name] }), item.name)); }) }), void 0) }), void 0)] }), void 0), _jsx("div", __assign({ className: "flex-shrink-0 flex border-t border-gray-200 p-4" }, { children: _jsx("a", __assign({ href: "#", className: "flex-shrink-0 w-full group block" }, { children: _jsxs("div", __assign({ className: "flex items-center" }, { children: [_jsx("div", { children: _jsx("img", { className: "inline-block h-9 w-9 rounded-full", src: "https://images.unsplash.com/photo-1517365830460-955ce3ccd263?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=8&w=256&h=256&q=80", alt: "" }, void 0) }, void 0), _jsxs("div", __assign({ className: "ml-3" }, { children: [_jsx("p", __assign({ className: "text-sm font-medium text-gray-700 group-hover:text-gray-900" }, { children: "Whitney Francis" }), void 0), _jsx("p", __assign({ className: "text-xs font-medium text-gray-500 group-hover:text-gray-700" }, { children: "View profile" }), void 0)] }), void 0)] }), void 0) }), void 0) }), void 0)] }), void 0) }), void 0) }), void 0), _jsxs("div", __assign({ className: "flex flex-col min-w-0 flex-1 overflow-hidden" }, { children: [_jsx("div", __assign({ className: "lg:hidden" }, { children: _jsxs("div", __assign({ className: "flex items-center justify-between bg-gray-50 border-b border-gray-200 px-4 py-1.5" }, { children: [_jsx("div", { children: _jsx("img", { className: "h-8 w-auto", src: "https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg", alt: "Workflow" }, void 0) }, void 0), _jsx("div", { children: _jsxs("button", __assign({ type: "button", className: "-mr-3 h-12 w-12 inline-flex items-center justify-center rounded-md text-gray-500 hover:text-gray-900", onClick: function () { return setSidebarOpen(true); } }, { children: [_jsx("span", __assign({ className: "sr-only" }, { children: "Open sidebar" }), void 0), _jsx(MenuIcon, { className: "h-6 w-6", "aria-hidden": "true" }, void 0)] }), void 0) }, void 0)] }), void 0) }), void 0), _jsxs("div", __assign({ className: "flex-1 relative z-0 flex overflow-hidden" }, { children: [_jsx("main", __assign({ className: "flex-1 relative z-0 overflow-y-auto focus:outline-none xl:order-last" }, { children: _jsx("div", __assign({ className: "absolute inset-0 py-6 px-4 sm:px-6 lg:px-8" }, { children: _jsx("div", { className: "h-full border-2 border-blue-200 border-dashed rounded-lg" }, void 0) }), void 0) }), void 0), _jsx("aside", __assign({ className: "hidden relative xl:order-first xl:flex xl:flex-col flex-shrink-0 w-96 border-r border-gray-200" }, { children: _jsx("div", __assign({ className: "absolute inset-0 py-6 px-4 sm:px-6 lg:px-8" }, { children: _jsx("div", { className: "h-full border-2 border-red-200 border-dashed rounded-lg" }, void 0) }), void 0) }), void 0)] }), void 0)] }), void 0)] }), void 0));
};
